GET http://localhost:5000/

### get servicios
GET http://localhost:5000/publicaciones

### create video
POST http://localhost:5000/publicaciones
Content-Type: application/json

{
  "nombre": "Carlos Tacury Guamen",
  "categoria": ["Eventos","Musica","locop"],
  "descripcion": "Soy un Dj profecional con disponibilidad los fines de semana cuento con equipacion de un disco movil.",
  "precio": 200,
  "direccion":{
      "provincia": "Chimborazo",
      "ciudad": "Riobamba",
      "calles": "9 de octubre y tarqui"  
  },
  "id_usuario": "054646rolip"
}




### GET Services
GET http://localhost:5000/publicacionesByUser/604249f5261f912458cf383f

### DELETE Services
DELETE http://localhost:5000/publicaciones/604a5d1c21b5d42ac4cb1aff

### UPDATE Services
PUT http://localhost:5000/publicaciones/604a5d1c21b5d42ac4cb1aff
Content-Type: application/json

{
 "direccion":{
      "provincia": "Tunguragua",
      "ciudad": "Ambato",
      "calles": "9 de octubre y tarqui"  
  },
  "categoria": ["Casa","jojo","jajaj"]
}